Repository alist-org/alist, pull requests merged in 2023-11, with the labels that each got.

#5457 feat(cloudreve): folder size count and switch
  drivers/cloudreve/driver.go
  drivers/cloudreve/meta.go
  drivers/cloudreve/types.go
  drivers/cloudreve/util.go
Labels: size/S

#5459 fix(weiyun): unmarshal overflow
  go.mod
  go.sum
Labels: size/XS

#5482 fix(115): fix driver package import and variable
  drivers/115/util.go
Labels: size/S

#5481 feat(115_share): add support for mounting 115 share links
  drivers/115_share/driver.go
  drivers/115_share/meta.go
  drivers/115_share/utils.go
  drivers/all.go
  go.mod
  go.sum
Labels: size/L

#5505 fix(mopan):302 Redirect
  drivers/mopan/driver.go
Labels: size/XS

#5519 chore: remove refs to deprecated io/ioutil
  drivers/google_drive/util.go
  internal/net/request_test.go
Labels: size/XS

#5420 fix(local): video file thumbnails not displaying on iOS Safari
  server/common/proxy.go
Labels: size/XS

#5526 add chaoxing and vtencent
  drivers/all.go
  drivers/chaoxing/driver.go
  drivers/chaoxing/meta.go
  drivers/chaoxing/types.go
  drivers/chaoxing/util.go
  drivers/vtencent/drive.go
  drivers/vtencent/meta.go
  drivers/vtencent/signature.go
  drivers/vtencent/types.go
  drivers/vtencent/util.go
  go.mod
  go.sum
Labels: size/XXL

#5560 fix(aliyundrive_open):Mitigation measures for AliOpen's 15-minute limit.
  drivers/aliyundrive_open/driver.go
Labels: size/XS

#5554 add show hidden option for crypt storage
  drivers/crypt/driver.go
  drivers/crypt/meta.go
Labels: size/XS

#5581 add error handling for webdav mkcol according to RFC 4918
  server/webdav/webdav.go
Labels: size/S
