Repository alist-org/alist, pull requests merged in 2023-08, with the labels that each got.

#4898 Add 123Pan Share
  drivers/123_share/driver.go
  drivers/123_share/meta.go
  drivers/123_share/types.go
  drivers/123_share/util.go
  drivers/all.go
Labels: size/L

#4921 general: enhance multi-thread downloader with cancelable context... (misc improvements)
  drivers/base/util.go
  drivers/crypt/driver.go
  drivers/mega/driver.go
  internal/model/args.go
  internal/net/request.go
  pkg/utils/io.go
  server/common/proxy.go
Labels: size/M

#4930 feat(search):paging search and search is_dir #4381
  internal/db/searchnode.go
  internal/model/search.go
  internal/search/bleve/search.go
Labels: size/S

#4939 feat(baidu_netdisk): add retry on most operations; improve stability
  drivers/115/driver.go
  drivers/123/driver.go
  drivers/189pc/utils.go
  drivers/aliyundrive_open/upload.go
  drivers/baidu_netdisk/driver.go
  drivers/baidu_netdisk/util.go
  drivers/baidu_photo/driver.go
  drivers/mediatrack/driver.go
  drivers/mopan/driver.go
  drivers/pikpak/driver.go
  drivers/quark_uc/driver.go
  drivers/terabox/driver.go
  drivers/thunder/driver.go
  drivers/weiyun/driver.go
  internal/errs/errors.go
  internal/fs/put.go
  pkg/utils/file.go
Labels: size/L

#4965 Perf upload and cache
  drivers/189pc/driver.go
  drivers/189pc/meta.go
  drivers/189pc/utils.go
  drivers/aliyundrive_open/driver.go
  drivers/aliyundrive_open/types.go
  drivers/aliyundrive_open/upload.go
  drivers/aliyundrive_open/util.go
  drivers/baidu_netdisk/driver.go
  drivers/baidu_netdisk/meta.go
  drivers/baidu_netdisk/types.go
  drivers/baidu_netdisk/util.go
  drivers/baidu_photo/driver.go
  drivers/baidu_photo/meta.go
  drivers/baidu_photo/types.go
  drivers/mopan/driver.go
  drivers/mopan/meta.go
  drivers/weiyun/driver.go
  drivers/weiyun/meta.go
  go.mod
  go.sum
  pkg/errgroup/errgroup.go
  pkg/utils/io.go
Labels: size/XL

#4987 Feat upload progress recovery
  drivers/189pc/help.go
  drivers/189pc/types.go
  drivers/189pc/utils.go
  drivers/baidu_netdisk/driver.go
  drivers/baidu_netdisk/meta.go
  drivers/baidu_photo/driver.go
  drivers/base/upload.go
  drivers/mopan/driver.go
  go.mod
  go.sum
  pkg/errgroup/errgroup.go
  pkg/utils/file.go
  pkg/utils/io.go
  pkg/utils/slice.go
Labels: size/L

#4945 feat: support webauthn login
  go.mod
  go.sum
  internal/authn/authn.go
  internal/bootstrap/data/setting.go
  internal/conf/const.go
  internal/db/db.go
  internal/db/user.go
  internal/model/user.go
  server/handles/webauthn.go
  server/middlewares/auth.go
  server/router.go
Labels: size/L

#5028 try to fix #4981
  internal/net/request.go
  internal/net/request_test.go
  internal/net/serve.go
  pkg/http_range/range.go
Labels: size/L

#5048 fix(lanzou):download not find file sgin
  drivers/lanzou/help.go
  drivers/lanzou/util.go
Labels: size/M

#5088 fix(lanzou): download not find data
  drivers/lanzou/help.go
  drivers/lanzou/util.go
Labels: size/S

#5091 fix(mopan):parameter error
  drivers/mopan/driver.go
  drivers/mopan/meta.go
  go.mod
  go.sum
Labels: size/S

#5100 docs: the README.md sets 644 permissions
  README.md
Labels: size/XS

#5111 general: fix updateTime, createTime and HashInfo
  drivers/alist_v3/driver.go
  drivers/alist_v3/types.go
  drivers/aliyundrive_share/types.go
  drivers/local/driver.go
  pkg/utils/hash.go
  pkg/utils/hash_test.go
  server/handles/fsread.go
Labels: size/M
