Repository alist-org/alist, pull requests merged in 2023-09, with the labels that each got.

#5145 general: fix form upload when ticked "As A Task"
  drivers/aliyundrive_open/upload.go
  internal/stream/stream.go
  server/handles/fsup.go
Labels: size/L

#5148 feat(crypt): enable filename_encoding for advanced users
  drivers/crypt/driver.go
  drivers/crypt/meta.go
  pkg/utils/str.go
Labels: size/S

#5151 feat(aliyun_open): fix date format
  drivers/aliyundrive_open/upload.go
Labels: size/XS

#5162 fix(webdav): http chunked request invalid
  internal/stream/stream.go
  pkg/utils/file.go
Labels: size/S

#5178 fix(crypt): fix 139cloud hack
  internal/stream/util.go
  pkg/http_range/range.go
Labels: size/M

#5180 Adaptation feature
  drivers/139/types.go
  drivers/139/util.go
  drivers/189pc/driver.go
  drivers/189pc/meta.go
  drivers/189pc/utils.go
  drivers/baidu_netdisk/driver.go
  drivers/baidu_photo/driver.go
  drivers/baidu_photo/types.go
  drivers/mopan/driver.go
  drivers/mopan/util.go
  drivers/pikpak/driver.go
  drivers/pikpak/types.go
  drivers/thunder/driver.go
  drivers/thunder/types.go
  drivers/weiyun/driver.go
  pkg/utils/hash.go
  pkg/utils/hash/gcid.go
Labels: size/XL

#5184 fix(lanzou):share folder sub file need pwd
  drivers/lanzou/util.go
Labels: size/XS

#5218 修复：OneDrive 覆盖上传大文件时会失败
  drivers/onedrive/util.go
  drivers/onedrive_app/util.go
Labels: size/XS

#5253 修复115驱动数据竞争导致的crash
  drivers/115/driver.go
Labels: size/XS

#5260 feat: sso compatibility mode
  internal/bootstrap/data/setting.go
  internal/conf/const.go
  server/handles/ssologin.go
  server/router.go
Labels: size/L

#5284 feat: crypt driver can load pre-generated thumbnails under the subdirectory
  drivers/crypt/driver.go
  drivers/crypt/meta.go
Labels: size/XS
