Repository alist-org/alist, pull requests merged in 2023-12, with the labels that each got.

#5693 fix: retry multipart file reset
  drivers/base/client.go
Labels: size/XS

#5690 feat(139): support new personal cloud api
  drivers/139/driver.go
  drivers/139/meta.go
  drivers/139/types.go
  drivers/139/util.go
Labels: size/XL

#5689 fix: 123 driver connect error
  drivers/123/util.go
  go.mod
  go.sum
Labels: size/L

#5722 Add support for client-side discoverable WebAuthn login
  go.mod
  go.sum
  server/handles/webauthn.go
Labels: size/M

#5733 feat(115):support 302 redirect
  drivers/115/driver.go
  drivers/115/meta.go
Labels: size/XS

#5706 feat: add ldap login support
  go.mod
  go.sum
  internal/bootstrap/data/setting.go
  internal/conf/const.go
  internal/model/setting.go
  server/handles/ldap_login.go
  server/router.go
Labels: size/L

#5751 Modify all API's in the open source project from aliyundrive.com to alipan.com to support ipv6 acceleration
  README.md
  README_cn.md
  README_ja.md
  drivers/aliyundrive/driver.go
  drivers/aliyundrive/util.go
  drivers/aliyundrive_open/meta.go
  drivers/aliyundrive_share/driver.go
  drivers/aliyundrive_share/util.go
Labels: size/M
