Repository alist-org/alist, pull requests merged in 2023-10, with the labels that each got.

#5316 Update util.go
  drivers/aliyundrive_open/util.go
Labels: size/XS

#5308 fix(terabox): encode parameters for `filemanager` api
  drivers/terabox/util.go
Labels: size/XS

#5331 wip: refactor offline download
  internal/bootstrap/data/setting.go
  internal/model/setting.go
  internal/offline_download/add.go
  internal/offline_download/all_test.go
  internal/offline_download/aria2/aria2.go
  internal/offline_download/aria2/notify.go
  internal/offline_download/base.go
  internal/offline_download/monitor.go
  internal/offline_download/tools.go
  internal/offline_download/util.go
  server/handles/aria2.go
Labels: size/XL

#5329 docs: minor language improvements
  README.md
Labels: size/XS

#5334 feat(google_drive):add hash_info,ctime,thumbnail
  drivers/google_drive/types.go
  drivers/google_drive/util.go
  pkg/utils/hash.go
Labels: size/S

#5346 fix: OnedriveAPP will report error when using cn
  drivers/onedrive_app/util.go
Labels: size/XS

#5356 fix(baidu):hash and error:2
  drivers/baidu_netdisk/driver.go
  drivers/baidu_netdisk/types.go
  drivers/baidu_netdisk/util.go
  internal/model/obj.go
  internal/stream/util.go
Labels: size/L

#5367 fix(115):limit request rate
  drivers/115/driver.go
  drivers/115/meta.go
Labels: size/M

#5373 feat(cloudreve): support thumbnail (close https://github.com/alist-org/alist/issues/5348)
  drivers/cloudreve/driver.go
  drivers/cloudreve/types.go
  drivers/cloudreve/util.go
Labels: size/M

#5394 fix: hash gcid empty file
  pkg/utils/hash/gcid.go
Labels: size/S

#5398 fix(aliyundrive_open): upload progress for normal upload
  drivers/aliyundrive_open/upload.go
Labels: size/XS

#5391 perf(webdav): support for cookies on webdav drive
  drivers/webdav/util.go
  pkg/gowebdav/client.go
Labels: size/S
