Repository alist-org/alist, pull requests merged in 2024-05, with the labels that each got.

#6397 fix(onedrive) fix Ctime/Mtime
  drivers/onedrive/driver.go
  drivers/onedrive/types.go
  drivers/onedrive/util.go
Labels: size/M

#6409 fix(115): disable NoOverwriteUpload
  drivers/115/meta.go
Labels: size/XS

#6392 CI: cache musl library in docker build workflow
  .github/workflows/build_docker.yml
  .github/workflows/release_docker.yml
  Dockerfile.ci
  build.sh
Labels: size/M

#6422 fix(test): ensure setupStorages is executed once
  internal/op/storage_test.go
Labels: size/XS

#6427 fix(189pc): FamilyID in FamilyInfoResp struct range overflow
  drivers/189pc/types.go
Labels: size/XS

#6431 feat(s3): server support generated url request
  go.mod
  go.sum
  server/s3/backend.go
  server/s3/list.go
  server/s3/logger.go
  server/s3/pager.go
  server/s3/server.go
  server/s3/utils.go
Labels: size/M

#6423 feat: add supports for netease music driver
  drivers/all.go
  drivers/netease_music/crypto.go
  drivers/netease_music/driver.go
  drivers/netease_music/meta.go
  drivers/netease_music/types.go
  drivers/netease_music/upload.go
  drivers/netease_music/util.go
  go.mod
  go.sum
Labels: size/XL

#6416 fix(sftp): reconnect to server when connection was broken (close #6403)
  drivers/sftp/driver.go
  drivers/sftp/util.go
Labels: size/M

#6443 feat(alist_v3): Optional pass UA to upstream remote
  drivers/alist_v3/driver.go
  drivers/alist_v3/meta.go
Labels: size/S

#6464 feat: add supports for thunderX driver
  drivers/all.go
  drivers/thunderx/driver.go
  drivers/thunderx/meta.go
  drivers/thunderx/types.go
  drivers/thunderx/util.go
Labels: size/XXL

#6478 feat(alias): support Rename and Remove
  drivers/alias/driver.go
  drivers/alias/meta.go
  drivers/alias/util.go
  internal/errs/errors.go
Labels: size/M

#6473 add 2FA support for mega
  drivers/mega/driver.go
  drivers/mega/meta.go
Labels: size/S

#6497 fix: pikpak captcha_required
  drivers/pikpak/driver.go
  drivers/pikpak/meta.go
  drivers/pikpak/util.go
  drivers/pikpak_share/driver.go
  drivers/pikpak_share/meta.go
  drivers/pikpak_share/util.go
Labels: size/L

#6496 feat: add `proxy_range` option for `139Yun` `Alias` `AList V3`
  drivers/139/meta.go
  drivers/alias/meta.go
  drivers/alias/util.go
  drivers/alist_v3/meta.go
  internal/driver/config.go
  internal/model/storage.go
  internal/op/driver.go
  server/common/proxy.go
  server/handles/down.go
  server/webdav/webdav.go
Labels: size/M

#6475 feat: add support for lark driver
  drivers/lark.go
  drivers/lark/driver.go
  drivers/lark/meta.go
  drivers/lark/types.go
  drivers/lark/util.go
  go.mod
  go.sum
Labels: size/XL

#6500 fix(mopan): update version
  go.mod
  go.sum
Labels: size/XS

#6501 fix(pikpak): refresh_token contention
  drivers/pikpak/driver.go
  drivers/pikpak_share/driver.go
  pkg/utils/oauth2.go
Labels: size/M

#6529 feat: add supports for thunder_browser driver
  drivers/all.go
  drivers/thunder_browser/driver.go
  drivers/thunder_browser/meta.go
  drivers/thunder_browser/types.go
  drivers/thunder_browser/util.go
  drivers/thunderx/driver.go
Labels: size/XXL
