Repository alist-org/alist, pull requests merged in 2024-02, with the labels that each got.

#5977 (fix ldap): An 'exiting by peer' exception occurred during the TLS con…
  server/handles/ldap_login.go
Labels: size/M

#5987 Fix: mopan
  drivers/mopan/driver.go
  drivers/mopan/meta.go
  drivers/quqi/driver.go
  go.mod
  go.sum
Labels: size/L

#6015 fix: WebDAV's creation data should be in RFC3339 format
  server/webdav/prop.go
Labels: size/XS

#6012 Fix/123pan driver
  drivers/123/driver.go
  drivers/123/util.go
Labels: size/S

#6054 Add docker image with ffmpeg release
  .github/workflows/build_docker.yml
  .github/workflows/release_docker.yml
  Dockerfile.ffmpeg
Labels: size/M

#6031 support for using unixsocket to connect to mysql
  internal/bootstrap/db.go
  internal/conf/config.go
Labels: size/XS

#6060 feat(search): search with meilisearch.
  go.mod
  go.sum
  internal/bootstrap/data/setting.go
  internal/conf/config.go
  internal/search/import.go
  internal/search/meilisearch/init.go
  internal/search/meilisearch/search.go
  pkg/utils/slice.go
Labels: size/L
