Repository alist-org/alist, pull requests merged in 2024-01, with the labels that each got.

#5787 fix(115):support null UserAgent
  drivers/115/driver.go
  drivers/115/util.go
Labels: size/M

#5810 feat: add ilanzou driver
  README.md
  README_cn.md
  README_ja.md
  drivers/all.go
  drivers/ilanzou/driver.go
  drivers/ilanzou/meta.go
  drivers/ilanzou/types.go
  drivers/ilanzou/util.go
Labels: size/XL

#5823 fix(net): Buf use Mutex
  internal/net/request.go
Labels: size/XS

#5844 ci: add android target to release build
  .github/workflows/release_android.yml
  build.sh
Labels: size/M

#5877 fix(chaoxing):fix JSON parsing error in `content` field
  drivers/chaoxing/types.go
  drivers/chaoxing/util.go
Labels: size/M

#5899 feat: add `quqi` driver
  drivers/all.go
  drivers/quqi/driver.go
  drivers/quqi/meta.go
  drivers/quqi/types.go
  drivers/quqi/util.go
  go.mod
  go.sum
Labels: size/XL

#5905 fix(google_photo): add support for streaming video, range requests
  drivers/google_photo/driver.go
  drivers/google_photo/util.go
Labels: size/M

#5910 fix(quqi): file extension duplication when rename and some missing form parameters
  drivers/quqi/driver.go
  drivers/quqi/util.go
Labels: size/M

#5920 fix(quqi): error returned when uploading a file that existed
  drivers/quqi/driver.go
  drivers/quqi/types.go
  drivers/quqi/util.go
Labels: size/M

#5926 fix(quqi): empty file link for no vip user
  drivers/quqi/driver.go
  drivers/quqi/types.go
  drivers/quqi/util.go
Labels: size/M

#5938 feat(quqi): add download link by quqi cdn
  drivers/quqi/driver.go
  drivers/quqi/meta.go
  drivers/quqi/types.go
  drivers/quqi/util.go
  go.mod
  go.sum
Labels: size/L

#5929 feat(dropbox): add root_namespace_id to access teams folder
  drivers/dropbox/driver.go
  drivers/dropbox/meta.go
  drivers/dropbox/types.go
  drivers/dropbox/util.go
Labels: size/M

#5957 二次加载 public/dist 资源的问题
  server/static/static.go
Labels: size/XS
