Repository alist-org/alist, pull requests merged in 2024-09, with the labels that each got.

#7117 fix(pikpak):fix an error when passing the user_id field
  drivers/pikpak/driver.go
  drivers/pikpak/meta.go
  drivers/pikpak/util.go
Labels: size/L

#7123 fix(webdav): memory leak in HttpServer
  internal/net/serve.go
Labels: size/S

#7124 fix(local): thumbnails oom
  drivers/local/driver.go
  drivers/local/meta.go
  drivers/local/token_bucket.go
Labels: size/M

#7132 Fix local proxy
  internal/bootstrap/config.go
  internal/op/fs.go
Labels: size/S

#7136 feat(pikpak&pikpak_share): add download address delay detection
  drivers/pikpak/driver.go
  drivers/pikpak/meta.go
  drivers/pikpak/util.go
  drivers/pikpak_share/driver.go
  drivers/pikpak_share/meta.go
  drivers/pikpak_share/util.go
Labels: size/L

#7150 fix(pikpak): fix nil pointer error
  drivers/pikpak/util.go
Labels: size/S

#7160 fix(google_photo) fix issue copy videos from google photo
  drivers/google_photo/driver.go
Labels: size/M

#7196 修改115UA
  drivers/115/util.go
Labels: size/XS

#7220 fix: dynamic update app version. (close #7198)
  drivers/115/util.go
  go.mod
  go.sum
Labels: size/M

#7232 feat(offline_download): add transmission (close #4102)
  go.mod
  go.sum
  internal/conf/const.go
  internal/offline_download/all.go
  internal/offline_download/tool/download.go
  internal/offline_download/transmission/client.go
  server/handles/offline_download.go
  server/router.go
Labels: size/L
