Repository alist-org/alist, pull requests merged in 2024-03, with the labels that each got.

#6124 fix(chaoxing): json cannot unmarshal content.uploadDate (close #6119)
  drivers/chaoxing/types.go
Labels: size/XS

#6133 Add support for Microsoft WebDAV
  server/webdav/prop.go
  server/webdav/webdav.go
Labels: size/XS

#6088 feat!: s3 server
  go.mod
  go.sum
  internal/bootstrap/data/setting.go
  internal/conf/const.go
  internal/model/setting.go
  server/router.go
  server/s3.go
  server/s3/backend.go
  server/s3/ioutils.go
  server/s3/list.go
  server/s3/logger.go
  server/s3/pager.go
  server/s3/server.go
  server/s3/utils.go
Labels: size/XL

#6130 refactor(setting): replace `polyfill.io`
  internal/bootstrap/data/setting.go
  internal/model/setting.go
Labels: size/S

#6160 feat(seafile): improve features, support access to encrypted library, etc
  drivers/seafile/driver.go
  drivers/seafile/meta.go
  drivers/seafile/types.go
  drivers/seafile/util.go
Labels: size/L

#6166 fix(mopan):upload error (close #6158)
  drivers/mopan/driver.go
Labels: size/XS

#6181 fix: webauthn logspam
  internal/bootstrap/data/user.go
  server/handles/user.go
Labels: size/S

#6146 feat(139): Refresh token periodically
  drivers/139/driver.go
  drivers/139/types.go
  drivers/139/util.go
Labels: size/M

#6206 fix(ci): replace dockerfile tag step may have no effect
  .github/workflows/build_docker.yml
  .github/workflows/release_docker.yml
Labels: size/XS

#6245 fix:url escape filename
  drivers/ipfs_api/driver.go
Labels: size/XS

#6248 fix(139): RefreshTokenResp is not serialized correctly
  drivers/139/util.go
Labels: size/XS

#6242 feat: single port s3 server
  cmd/server.go
  internal/bootstrap/data/setting.go
  internal/conf/config.go
  internal/conf/const.go
  server/router.go
  server/s3.go
  server/s3/backend.go
  server/s3/server.go
  server/s3/utils.go
Labels: size/M

#6273 fix: 解决多吉云临时秘钥两个小时过期的问题
  drivers/s3/doge.go
  drivers/s3/driver.go
Labels: size/S

#6282 style: use width instead of height to adapt to different rendering framwork
  README.md
  README_cn.md
  README_ja.md
Labels: size/XS

#6270 feat(crypt): force stream upload for supported drivers
  drivers/189pc/driver.go
  drivers/aliyundrive_open/upload.go
  drivers/crypt/driver.go
  internal/model/obj.go
  internal/stream/stream.go
Labels: size/M

#6277 fix: Doge 重置秘钥之后未重新获取客户端导致403
  drivers/s3/driver.go
Labels: size/XS
