Repository alist-org/alist, pull requests merged in 2024-07, with the labels that each got.

#6673 fix(drivers/iLanZou): resolve resource access issue on iLanZou drive
  drivers/ilanzou/driver.go
  drivers/ilanzou/util.go
Labels: size/L

#6692 feat(thunderBrowser): add automatically generate UserAgent
  drivers/thunder_browser/driver.go
  drivers/thunder_browser/meta.go
  drivers/thunder_browser/util.go
Labels: size/L

#6696 feat: add support for halalcloud driver
  drivers/all.go
  drivers/halalcloud/driver.go
  drivers/halalcloud/meta.go
  drivers/halalcloud/options.go
  drivers/halalcloud/types.go
  drivers/halalcloud/util.go
  go.mod
  go.sum
  pkg/utils/io.go
Labels: size/XXL

#6648 feat: add pikpak offline download function
  drivers/pikpak/driver.go
  drivers/pikpak/types.go
  internal/offline_download/all.go
  internal/offline_download/pikpak/pikpak.go
  internal/offline_download/pikpak/util.go
  internal/offline_download/tool/add.go
  internal/offline_download/tool/download.go
Labels: size/L

#6683 Fix S3 Implementation bug & Support AWS Signature V2
  go.mod
  go.sum
  server/s3/backend.go
Labels: size/S

#6740 chore: update polyfill URL due to service unavailability and supply chain attack risk
  internal/bootstrap/data/setting.go
Labels: size/XS

#6762 fix: ignore os.ErrClosed error on repeated FileStream close operations
  internal/stream/stream.go
Labels: size/XS

#6775 fix(pikpak): add captcha_token generation function
  drivers/pikpak/driver.go
  drivers/pikpak/types.go
  drivers/pikpak/util.go
Labels: size/L

#6788 fix(pikpak): fix captcha_token not refreshing correctly
  drivers/pikpak/driver.go
  drivers/pikpak/types.go
  drivers/pikpak/util.go
Labels: size/M

#6793 feat: add support for Onedrive Sharelink driver
  drivers/all.go
  drivers/onedrive_sharelink/driver.go
  drivers/onedrive_sharelink/meta.go
  drivers/onedrive_sharelink/types.go
  drivers/onedrive_sharelink/util.go
Labels: size/XL

#6814 fix(123pan): add warning for mismatched file count when listing files
  drivers/123/driver.go
  drivers/123/types.go
  drivers/123/util.go
Labels: size/S

#6859 perf(123pan): optimize rate limiting
  drivers/123/driver.go
  drivers/123/util.go
  drivers/123_share/driver.go
  drivers/123_share/util.go
Labels: size/M

#6862 fix(lanzou):not find file page param
  drivers/lanzou/driver.go
  drivers/lanzou/meta.go
  drivers/lanzou/util.go
Labels: size/XS

#6880 Update alist-org/gofakes3 to v0.0.7, support create folder in PutObject.
  go.mod
  go.sum
  server/s3/backend.go
Labels: size/S
