Repository alist-org/alist, pull requests merged in 2024-04, with the labels that each got.

#6283 fix: typos
  internal/net/util.go
  server/handles/ssologin.go
Labels: size/XS

#6288 feat(189pc): add family transfer upload
  drivers/189pc/driver.go
  drivers/189pc/help.go
  drivers/189pc/meta.go
  drivers/189pc/types.go
  drivers/189pc/utils.go
  pkg/utils/time.go
Labels: size/XL

#6291 fix(s3): don't bind s3 port if s3 is not enabled
  cmd/server.go
  server/s3.go
Labels: size/S

#6316 fix: 修复Meilisearch相关配置无法通过环境变量配置
  internal/conf/config.go
Labels: size/XS

#6324 feat: Add token login for Seafile
  drivers/seafile/meta.go
  drivers/seafile/util.go
Labels: size/XS

#6339 fix: correct the download url got by Cloudreve driver
  drivers/cloudreve/driver.go
Labels: size/XS

#6346 使存储初始化顺序可控，防止加密存储初始化失败
  internal/bootstrap/storage.go
  internal/db/storage.go
Labels: size/XS

#6357 feat(123_share): add access token
  drivers/123_share/driver.go
  drivers/123_share/meta.go
  drivers/123_share/util.go
Labels: size/M

#6372 Webdav make sure Mtime >= Ctime
  server/webdav/util.go
  server/webdav/webdav.go
Labels: size/S

#6373 fix(BaiduNetdisk) fix cached Ctime/Mtime
  drivers/baidu_netdisk/driver.go
Labels: size/S

#6389 Perf: use io copy with buffer
  drivers/123/driver.go
  drivers/189pc/utils.go
  drivers/aliyundrive/driver.go
  drivers/aliyundrive_open/upload.go
  drivers/baidu_netdisk/driver.go
  drivers/baidu_photo/driver.go
  drivers/chaoxing/driver.go
  drivers/ilanzou/driver.go
  drivers/mediatrack/driver.go
  drivers/pikpak/util.go
  drivers/quark_uc/driver.go
  drivers/smb/util.go
  drivers/thunder/util.go
  internal/net/request.go
  internal/net/serve.go
  internal/net/util.go
  internal/stream/stream.go
  pkg/gowebdav/client.go
  pkg/utils/file.go
  pkg/utils/hash.go
  pkg/utils/hash_test.go
  pkg/utils/io.go
Labels: size/M
