Repository alist-org/alist, pull requests merged in 2024-08, with the labels that each got.

#6560 修复：数据库不是sqlite3时会乱序的bug
  internal/bootstrap/data/setting.go
  internal/db/meta.go
  internal/db/settingitem.go
  internal/db/storage.go
  internal/db/user.go
  internal/db/util.go
  internal/model/setting.go
Labels: size/S

#6921 feat: add support for lenovonas_share driver
  drivers/all.go
  drivers/lenovonas_share/driver.go
  drivers/lenovonas_share/meta.go
  drivers/lenovonas_share/types.go
  drivers/lenovonas_share/util.go
Labels: size/L

#6923 feat: invalidate token on logout
  server/common/auth.go
  server/handles/auth.go
  server/router.go
Labels: size/M

#6938 fix(halalcloud): fix some custom fields not taking effect & update appID and appSecret
  drivers/halalcloud/meta.go
  drivers/halalcloud/util.go
Labels: size/S

#6925 feat: Persistant Task
  go.mod
  go.sum
  internal/bootstrap/config.go
  internal/bootstrap/data/data.go
  internal/bootstrap/data/task.go
  internal/bootstrap/task.go
  internal/conf/config.go
  internal/db/db.go
  internal/db/tasks.go
  internal/fs/copy.go
  internal/model/task.go
  internal/offline_download/tool/add.go
  internal/offline_download/tool/download.go
  internal/offline_download/tool/transfer.go
  internal/offline_download/tool/util.go
Labels: size/L

#6960 fix(halalcloud): fix the timeout issue when logging in
  drivers/halalcloud/driver.go
  drivers/halalcloud/util.go
Labels: size/XS

#6954 feat(115): add offline download tool (close #6888)
  drivers/115/driver.go
  go.mod
  go.sum
  internal/offline_download/115/client.go
  internal/offline_download/all.go
  internal/offline_download/tool/add.go
  internal/offline_download/tool/download.go
Labels: size/L

#6953 fix: upload to ChaoxingxingGroupCloud failed
  drivers/chaoxing/types.go
Labels: size/L

#6959 feat: add support for quark tv driver and uc tv driver
  drivers/all.go
  drivers/quark_uc_tv/driver.go
  drivers/quark_uc_tv/meta.go
  drivers/quark_uc_tv/types.go
  drivers/quark_uc_tv/util.go
Labels: size/XL

#6994 fix(189pc): InvalidSessionKey
  drivers/189pc/utils.go
Labels: size/S

#6996 feat(115): update qrcode source list
  drivers/115/meta.go
  drivers/115/util.go
  drivers/115_share/meta.go
  go.mod
  go.sum
Labels: size/M

#6988 feat(s3): using internal download method in proxy
  drivers/s3/driver.go
Labels: size/S

#7017 fix(pikpak): fix the problem that refresh_token cannot be obtained
  drivers/pikpak/driver.go
  drivers/pikpak/meta.go
  drivers/pikpak/util.go
Labels: size/L

#6989 ci(docker): using docker build args instead of extra dockerfile for ffmpeg
  .github/workflows/build_docker.yml
  .github/workflows/release_docker.yml
  Dockerfile
  Dockerfile.ci
  Dockerfile.ffmpeg
Labels: size/M

#7003 fix:gzip body导致的乱码
  internal/net/serve.go
Labels: size/S

#7024 fix(pikpak): modify the processing logic of CaptchaToken
  drivers/pikpak/driver.go
  drivers/pikpak/meta.go
  drivers/pikpak/util.go
Labels: size/L

#7045 fix(pikpak_share): add captcha_token generation function
  drivers/pikpak_share/driver.go
  drivers/pikpak_share/meta.go
  drivers/pikpak_share/types.go
  drivers/pikpak_share/util.go
Labels: size/L

#7050 fix(pikpak):fix webdav upload issue
  drivers/pikpak/driver.go
  drivers/pikpak/types.go
  drivers/pikpak/util.go
Labels: size/L

#7056 fix: fix log format
  cmd/lang.go
Labels: size/XS

#7041 Fix os.create failure, while the name of downloaded file is empty in offline_download
  internal/offline_download/http/client.go
Labels: size/S

#7035 fix(search): BuildIndex concurrency error
  internal/errs/search.go
  internal/op/fs.go
  internal/search/build.go
  internal/search/search.go
  pkg/mq/mq.go
  server/handles/index.go
Labels: size/M

#7059 feat: add kodbox storage
  drivers/all.go
  drivers/kodbox/driver.go
  drivers/kodbox/meta.go
  drivers/kodbox/types.go
  drivers/kodbox/util.go
Labels: size/L

#7073 chore(local): decrease mass ffmpeg logs
  drivers/local/util.go
Labels: size/S
